# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmation',
            name='logo',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
