# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-30 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_customization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customemail',
            name='logo',
            field=models.ImageField(upload_to='logos'),
        ),
    ]
