# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180408_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettemplate',
            name='message_ticket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
