# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_tickettemplate_message_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettemplate',
            old_name='name_ticket',
            new_name='name_design_template',
        ),
        migrations.AlterField(
            model_name='tickettemplate',
            name='message_ticket',
            field=models.CharField(default='namedesign', max_length=255),
            preserve_default=False,
        ),
    ]
