# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180408_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='event_name',
        ),
        migrations.RemoveField(
            model_name='customization',
            name='select_event',
        ),
    ]
