# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180408_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
