# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 21:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_customization_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customization',
            old_name='event',
            new_name='select_event',
        ),
    ]
