# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20180408_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customization',
            name='select_event',
        ),
    ]
