# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_customization_select_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customization',
            name='custom_email',
        ),
        migrations.RemoveField(
            model_name='customization',
            name='ticket_template',
        ),
        migrations.RemoveField(
            model_name='customization',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomEmail',
        ),
        migrations.DeleteModel(
            name='Customization',
        ),
        migrations.DeleteModel(
            name='TicketTemplate',
        ),
    ]
