# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 13:51
from __future__ import unicode_literals

from django.db import migrations


def template_default(apps, schema_editor):
    Country = apps.get_model("customization", "Country")
    us = Country.objects.create(
        name="United States", prefix="US",
    )

    Tax = apps.get_model("report", "Tax")
    btw = Tax.objects.filter(
        name="BTW"
    ).first()

    CountryTax = apps.get_model("report", "CountryTax")
    CountryTax.objects.create(
        tax=btw, country=us, vat_rate=6,
    )

    EventbriteData = apps.get_model("report", "EventbriteData")
    EventbriteData.objects.create(
        name="Eventbrite Inc.",
        country=us,
        address="155 5th St, San Francisco, CA",
        vat_number="vatinUS",
        commerce_chamber="ccUS",
        web="www.eventbrite.com",
    )

class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(template_default),
        migrations.RunPython(netherlands),
        migrations.RunPython(unitedstates),
    ]
