# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettemplate',
            name='footer_description',
            field=models.CharField(default=None, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='tickettemplate',
            name='show_event_sequence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tickettemplate',
            name='show_ticket_type_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tickettemplate',
            name='show_ticket_type_sequence',
            field=models.BooleanField(default=False),
        ),
    ]
