# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.11 on 2018-04-12 14:57
=======
# Generated by Django 1.11.11 on 2018-04-12 13:21
>>>>>>> first steps to auto webhook
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='webhook_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
