# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customemail',
            name='logo',
            field=models.ImageField(max_length=255, upload_to='logos'),
        ),
    ]
