# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 13:51
from __future__ import unicode_literals

from django.db import migrations


def template_default(apps, schema_editor):
    BaseTicketTemplate = apps.get_model("customizations", "BaseTicketTemplate")
    BaseTicketTemplate.objects.create(
        template_source='tickets/template_default.html',
        name="Default design",
        preview="../../static/images/preview_default.png",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0002_auto_20180425_1146'),
    ]

    operations = [
        migrations.RunPython(template_default),
    ]
