# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '002_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetickettemplate',
            name='content_html',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customemail',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tickettemplate',
            name='footer_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickettemplate',
            name='message_ticket',
            field=models.TextField(),
        ),
    ]
