# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0002_customemail_image_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='pdf_ticket_attach',
            field=models.BooleanField(default=True),
        ),
    ]
