# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0002_ticketsequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsequence',
            name='event_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketsequence',
            name='ticket_type_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
