# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '002_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='customemail',
            name='image_partner',
            field=models.ImageField(default='', max_length=255, upload_to='partner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customemail',
            name='image_partner_local',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customemail',
            name='image_partner_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customemail',
            name='image_partner_path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customemail',
            name='image_partner_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
