# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0002_auto_20180425_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettemplate',
            name='footer_description',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
