# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0002_customization_webhook_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customization',
            name='webhook_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
