# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-26 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0003_customization_pdf_ticket_attach'),
    ]

    operations = [
        migrations.AddField(
            model_name='customemail',
            name='image_partner_local',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customemail',
            name='image_partner_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customemail',
            name='image_partner_path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customemail',
            name='image_partner_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
