# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-04 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0003_auto_20180504_1029'),
        ('customizations', '0003_auto_20180504_1113'),
    ]

    operations = [
    ]
