# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 13:51
from __future__ import unicode_literals

from django.db import migrations


def template_hero(apps, schema_editor):
    BaseTicketTemplate = apps.get_model("customizations", "BaseTicketTemplate")
    BaseTicketTemplate.objects.create(
        template_source='tickets/hero_design.html',
        name="Hero design",
        preview="../../static/images/hero_design.png",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0003_add_default_template'),
    ]

    operations = [
        migrations.RunPython(template_hero),
    ]