# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0003_auto_20180425_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketsequence',
            name='barcode',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
