# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-07 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0004_merge_20180504_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettemplate',
            old_name='show_ticket_type_price',
            new_name='hide_ticket_type_price',
        ),
    ]
