# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0004_ticketsequence_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsequence',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
