# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 13:51
from __future__ import unicode_literals

from django.db import migrations


def template_geo(apps, schema_editor):
    BaseTicketTemplate = apps.get_model("customizations", "BaseTicketTemplate")
    BaseTicketTemplate.objects.create(
        template_source='tickets/geo_design.html',
        name="Geo design",
        preview="../../static/images/geo_design.png",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0004_add_hero_template'),
    ]

    operations = [
        migrations.RunPython(template_geo),
    ]