# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-07 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0005_auto_20180507_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='pdf_ticket_attach',
            field=models.NullBooleanField(default=True),
        ),
    ]
