# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-07 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0006_customization_pdf_ticket_attach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customemail',
            name='message',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='customization',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tickettemplate',
            name='footer_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tickettemplate',
            name='message_ticket',
            field=models.CharField(max_length=400),
        ),
    ]
