# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-09 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0007_auto_20180507_2023'),
        ('customizations', '003_data'),
    ]

    operations = [
    ]
