# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 14:46
from __future__ import unicode_literals

from django.db import migrations


def template_default(apps, schema_editor):
    BaseTicketTemplate = apps.get_model("customizations", "BaseTicketTemplate")
    BaseTicketTemplate.objects.create(
        template_source='tickets/template_default.html',
        name="Default design",
        preview="../../static/images/preview_default.png",
    )


def template_hero(apps, schema_editor):
    BaseTicketTemplate = apps.get_model("customizations", "BaseTicketTemplate")
    BaseTicketTemplate.objects.create(
        template_source='tickets/hero_design.html',
        name="Hero design",
        preview="../../static/images/hero_design.png",
    )


def template_geo(apps, schema_editor):
    BaseTicketTemplate = apps.get_model("customizations", "BaseTicketTemplate")
    BaseTicketTemplate.objects.create(
        template_source='tickets/geo_design.html',
        name="Geo design",
        preview="../../static/images/geo_design.png",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(template_default),
        migrations.RunPython(template_hero),
        migrations.RunPython(template_geo),
    ]
