# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-25 14:46
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group


def add_group(apps, schema_editor):
    group_name = "admin"
    if not Group.objects.filter(name=group_name).exists():
        group = Group(name=group_name)
        group.save()


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_group),
    ]
